evidence = {
    "Camera Logs": "CAMERA 03\n22:47 - SIGNAL LOST\n22:52 - SIGNAL RESTORED\n\nCAUSE: MANUAL DISCONNECT",
    "Server Access Logs": "22:52\nTERMINAL: SRV-03\nUSER: M. SEN\nACCESS: GRANTED",
    "Door Logs": "22:42 - MAYA SEN - ENTRY\n23:03 - MAYA SEN - EXIT",
    "Phone Records": "OUTGOING CONNECTION\nDESTINATION: INTERNAL LOCKDOWN\nUSER: M. SEN",
    "Ravi's Terminal": "TERMINAL: SRV-02\nWARNING: UNAUTHORIZED SERVER ACCESS DETECTED\n\nMESSAGE SENT TO: RAVI",
    "Deleted File": "FILE: lockdown_override.log\n\n23:17 - OVERRIDE ACTIVATED\nUSER: M. SEN",
}